name: Run Cursor Pro Keep Alive

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-project:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check IP Address
      run: |
        echo "GitHub Actions Runner IP :"
        curl -s https://api.ipify.org
        curl -s http://checkip.amazonaws.com
        curl -s https://ipinfo.io/ip
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymysql
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        
    - name: Set environment variables
      run: |
        echo "CHROME_PATH=/usr/bin/chromium-browser" >> $GITHUB_ENV
        echo "CHROME_ARGS=--headless=new --no-sandbox --disable-dev-shm-usage" >> $GITHUB_ENV
        
    - name: Run cursor_pro_keep_alive
      env:
        WEBSHARE_API_KEY: ${{ secrets.WEBSHARE_API_KEY }}
      run: |
        python cursor_pro_keep_alive.py 